Coefficients:
  energy:
    Distribution: "normal"
    Range: [5.0, 1]
  
  radialIntensity:
    Distribution: "normal"
    Range: [2.0, 0.5]
  
  transverseIntensity:
    Distribution: "normal"
    Range: [1.0, 0.2]
  
  pressure:
    Distribution: "none"
    Range: 0.0
  
  radialVelocity:
    Distribution: "none"
    Range: 0.0
  
  transverseVelocity:
    Distribution: "none"
    Range: 0.0
  
  inPhaseQuadratic:
    Distribution: "normal"
    Range: [10.0, 3]
  
  symmetryQuadratic:
    Distribution: "normal"
    Range: [2.0, 0.5]
  
  inPhaseLinear:
    Distribution: "none"
    Range: 0.0
  
  symmetryLinear:
    Distribution: "none"
    Range: 0.0
  
  totalGainsLinear:
    Distribution: "none"
    Range: 0.0
  
  totalGainsQuadratic:
    Distribution: "none"
    Range: 0.0

InputFormat:
  FormatChoices: ["Ambisonics"]

  Ambisonics:
    Range: [3, 4, 5]
  
  SpeakerLayout:
    Range: [
      "layout_7_0_4",
      "layout_5_0",
      "layout_9_0_1"
      ]

OutputFormat:
  FormatChoices: ["SpeakerLayout"]

  Ambisonics:
    Range: [3, 4, 5]
  
  SpeakerLayout:
    Range: [
      "layout_3_0_2", 
      "layout_4_0", 
      "layout_4_0_2", 
      "layout_5_0", 
      "layout_7_0_4", 
      "layout_9_0_4"
      ]